default_lang: en

host: "http://localhost:5001"

thesis:
    urn_prefix: 'urn:thesis-'

store:
  builtin_users:
    package: Hash
    options:
      init_data:
        # stored password authentication
        - login: einstein
          # password is same as login
          # crypt a password with 'bmkpasswd [password]' in the shell
          password: '$2a$08$p1zhJInkNqy9nvMFsEPde./hU4ERNQuX2UQUjZA/ddrp1uUXikn/6'
          _id: 1234
          super_admin: 1

authentication:
  package: LibreCat::Auth::Multi
  options:
    methods:
      # password auth against users in config
      - package: LibreCat::Auth::Bag
        options:
          store: builtin_users
          username_attr: login
      # password auth against database users
      - package: LibreCat::Auth::Bag
        options:
          store: search
          bag: researcher
          username_attr: login
      # LDAP auth
      - package: LibreCat::Auth::LDAP
        options:
          host: 'ldaps://ug-sub-s1.sub.uni-goettingen.de'
          #base: '********'
          #password: '********'
          auth_base: 'UG-SUB\\%s'
          search_filter: '(sAMAccountName=%s)'
          search_base: 'DC=DomainDnsZones,DC=sub,DC=uni-goettingen,DC=de'
          search_attr: 'sAMAccountName'

user:
  sources:
    - store: builtin_users
      username_attr: login
    - store: search
      bag: researcher
      username_attr: login
